CREATE DATABASE IF NOT EXISTS projet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE projet;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (firstname, lastname, email, phone, password) VALUES 
('John', 'Doe', 'john@example.com', '+221771234567', '$2y$10$SN1.8T3r4bH5qJ2l9K0p.eFzV7e5z5bnG5.nT5dG5qJ5qJ5qJ5qJ5qJ');
